There are several advantages of PyTorch over TensorFlow:

1. Dynamic computational graph: PyTorch utilizes a dynamic computational graph, which allows for more flexibility during model development. It enables users to define and modify computational graphs on-the-fly, making it easier to debug and experiment with different network architectures.
2. Easier debugging and prototyping: PyTorch's imperative programming style makes it more intuitive and easier to debug compared to TensorFlow's static graph approach. Developers can use Python's native debugging tools, such as pdb, to step through the code and inspect variables at runtime.
3. Pythonic and user-friendly API: PyTorch's API is designed to be more pythonic and user-friendly, with a simpler syntax that is easier to learn and use. The framework integrates well with the Python ecosystem, making it convenient to use popular libraries and tools for tasks such as data loading and visualization.
4. Extensive community support: PyTorch has gained significant popularity within the research community, leading to a large and active user community. This means there are numerous online resources, tutorials, and pre-trained models available, making it easier to get help and accelerate development.
5. Dynamic neural networks: PyTorch allows for the creation of dynamic neural networks, where the structure of the network can change for each input. This feature is particularly useful for applications such as natural language processing, where the length of input sequences may vary.
6. Easier deployment to production: PyTorch's deployment process is generally considered more straightforward compared to TensorFlow. The framework offers tools like TorchScript and TorchServe, which facilitate model serialization, optimization, and serving in production environments.
7. Strong presence in research: PyTorch has gained popularity among researchers due to its flexibility and ease of use. Many state-of-the-art research papers release their code in PyTorch, making it easier for others to reproduce and build upon their work.

It's important to note that TensorFlow also has its own strengths and advantages, such as a mature ecosystem, support for distributed computing, and extensive deployment options. The choice between PyTorch and TensorFlow often depends on specific requirements and preferences of the project or the user.

In [1]:
import torch
torch.__version__

'2.0.1+cu118'

In [7]:
# defining a scalar
my_scalar = torch.tensor(7)
print(my_scalar)
print('ndim: ', my_scalar.ndim)
print('item: ', my_scalar.item())

tensor(7)
ndim:  0
item:  7


In [15]:
#defining a vector
my_vector = torch.tensor([1, 2])
print(my_vector)
print('ndim:  ', my_vector.ndim)
print('shape: ', my_vector.shape)

tensor([1, 2])
ndim:   1
shape:  torch.Size([2])


In [14]:
# defining a matrix
my_matrix = torch.tensor([[1, 2],
                          [3, 4]])
print(my_matrix)
print('ndim:  ', my_matrix.ndim)
print('shape: ', my_matrix.shape)

tensor([[1, 2],
        [3, 4]])
ndim:   2
shape:  torch.Size([2, 2])


In [16]:
# defining a tensor
my_tensor = torch.tensor([[[1, 2, 3],
                           [3, 6, 9],
                           [2, 4, 5]]])
print(my_tensor)
print('ndim:  ', my_tensor.ndim)
print('shape: ', my_tensor.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
ndim:   3
shape:  torch.Size([1, 3, 3])


In [26]:
# generating a random tensor
my_random_tensor = torch.rand(size=(2, 3))
my_random_tensor, my_random_tensor.dtype

(tensor([[0.7972, 0.0901, 0.1771],
         [0.3144, 0.2017, 0.7452]]),
 torch.float32)

In [29]:
my_random_image = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]
my_random_image.ndim

3

In [31]:
zeros = torch.zeros(size=(2,3))
ones = torch.ones(size=(2,3))
print(zeros, zeros.dtype)
print(ones, ones.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.float32


In [35]:
counter = torch.arange(start=1, end=10, step=2, dtype=torch.float32)
counter

tensor([1., 3., 5., 7., 9.])

In [36]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [37]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [41]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
output = linear(tensor_A)
print(output)

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)


In [44]:
torch.min(output), torch.max(output), torch.mean(output), torch.sum(output)

(tensor(0.1309, grad_fn=<MinBackward1>),
 tensor(6.7469, grad_fn=<MaxBackward1>),
 tensor(1.7470, grad_fn=<MeanBackward0>),
 tensor(31.4464, grad_fn=<SumBackward0>))

In [46]:
print(f"where max value happens is {torch.argmax(output)}")

where max value happens is 12
